import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Box, Container } from '@chakra-ui/react';

// Providers
import { ChakraUIProvider } from '@providers/index';

// Components
import { Header } from '@components/layout/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <ChakraUIProvider>
        <Box
          background="url('./background.png') no-repeat center"
          backgroundSize="cover"
        >
          <Header />
          <Container as="main" minH="100vh">
            {children}
          </Container>
        </Box>
      </ChakraUIProvider>
    </body>
  </html>
);

export default RootLayout;
