import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { Container } from '@chakra-ui/react';

// Providers
import { ChakraUIProvider, ReactQueryProvider } from '@providers/index';

// Components
import { Header } from '@components/layout/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body
      className={inter.className}
      style={{
        background: "url('/background.png') no-repeat center",
        backgroundSize: 'cover',
      }}
    >
      <ChakraUIProvider>
        <ReactQueryProvider>
          <Header />
          <Container as="main" minH="100vh">
            {children}
          </Container>
        </ReactQueryProvider>
      </ChakraUIProvider>
    </body>
  </html>
);

export default RootLayout;
