import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("Re-render");

  return (
    <html lang="en">
      <body className={inter.className}>
        <section
          style={{
            width: "300px",
            height: "500px",
            padding: "20px",
            boxSizing: "border-box",
            border: "1px solid",
          }}
        >
          <p
            style={{
              padding: "0 0 20px 0",
            }}
          >
            Aside
          </p>
          <Navigation />
        </section>
        <section className="body">{children}</section>
      </body>
    </html>
  );
}
